### PR TITLE
Add "cant attend" button and list of unattendees

### PR DESCRIPTION
**Pull request by hardfire**
This works in theory, 
the only issue is that "can't attend" button is disabled in the beginning because isAttendee is false by default. I'm still not sure if we should extend isAttendee or just handle this in patchbay-gatherings.

### CODE REVIEW

**Comment by mixmix** [comment]
I'll have a closer look tmrw.
Just quickly, I've been wondering a tidy way to pass your key around....
make sure you merge the current master branch in, then check out : `plugs/gathering/sync/launch-modal.js` and see where I've added `myKey` and where it's coming from with patchcore (keys.sync.id)

**Comment by hardfire** [comment]
Awesome, looking at `launch-modal.js` now i understand where the opts are coming from :D
Updated the pull request with
 - filter "cant Come" based on user's Key
 - fixed minor lint issue from master

**Comment by hardfire** [comment]
@mixmix sure! i dont have access to this repository i think though.

**Comment by mixmix** [comment]
Oh I thought I...Oh no I asked a friend to make me admin so I could. My
bad, sorry.

Will fix when I get home

**Pull request merged**
