### PR TITLE
Updates readme and introduces .npmrc

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by christianbundy** [comment]
Thanks! Could you help me understand the meaning of the `.npmrc` file? I'm familiar with setting `package-lock=false` but haven't set a registry before. What does that do?

**Comment by sainianubhav** [comment]
For devs who have internal/private registry. This file and setting will always install from public npm registry.

**Comment by christianbundy** [comment]
Thanks for the info. Does that mean that the would break ssb-npm, which I think uses a P2P registry hosted on SSB?

cc: @cel @noffle are you more familiar with this?

**Comment by sainianubhav** [comment]
> Thanks for the info. Does that mean that the would break ssb-npm, which I think uses a P2P registry hosted on SSB?

Wait, you install npm packages from private registry?

**Comment by christianbundy** [comment]
I think so, see: https://github.com/noffle/ssb-npm-101

**Comment by christianbundy** [comment]
It looks like we're just setting the same default value again, is there a benefit to that? I think that if developers want to configure a private/internal registry they should configure it, but I don't think we should redeclare default options (https://docs.npmjs.com/misc/config#registry).

**Pull request closed without merging**
